name: csi-driver-lvm
version: 0.8.1
description: local persistend storage for lvm
appVersion: v0.8.1
apiVersion: v1
keywords:
- storage
- block-storage
- volume
home: https://metal-stack.io
sources:
- https://github.com/metal-stack
